name: HelpPlus
version: 1.2
main: sk.tomsik68.helpplus.HelpPlus
database: true
description: This plugin provides useful information about your commands
author: tomsik68<tomsik68@gmail.com>
commands:
  help:
    description: Brings on help
    usage: /<command> [page], /<command> <plugin> [page], /<command> [command]
    aliases: ['h+','hp']
  h+:
    description: Brings on help
    aliases: ['help','hp']
    usage: /<command> [page], /<command> <plugin> [page], /<command> [command]
  hp:
    description: Brings on help
    aliases: ['h+','hp']
    usage: /<command> [page], /<command> <plugin> [page], /<command> [command]
  hplisting:
    description: Creates listing of all commands & permissions into single text file.
    usage: /<command>
  hpexport:
    description: Exports specified command(s) into config file for overriding.
    usage: /hpexport <command name> | /hpexport -p <pattern>
permissions:
  helpplus.help:
    description: Can be disabled via config file. Grants help-related commands. Defaultly true
    default: true
  helpplus.hpexport:
    description: Allows /hpexport