name: HelpPlus
version: 0.81
author: Tomsik68<tomsik68@gmail.com>
main: sk.tomsik68.helpplus.HelpPlus
database: true
description: A plugin which provides helpful information about your commands.
commands:
    help:
        description: Displays help about all your commands.
        aliases: ['hp','h+']
    h+:
        description: Alias to help
        aliases: ['hp','help']
    hp:
        description: Alias to help
        aliases: ['h+','help']
    hplisting:
        description: Lists all your commands and permission nodes.
        permission: helpplus.listing