name: HelpPlus
main: sk.tomsik68.helpplus.HelpPlus
author: Tomsik68
version: 0.2
description: Plugin which provides helpful information about commands
commands:
    hp:
        usage: /hp [page]
        aliases: /help
        description: Displays help
    help:
        usage: /help [page]
        aliases: /hp
        description: Displays help
